# install.packages("shiny")
library(shiny)
library("dplyr")
library("ggplot2")
library("plotly")
library("rsconnect")
library("plotly")
library("rsconnect")
library(tidyverse)

source("ui.R")
source("server.R")
# Runs the application (both ui and server)
shinyApp(ui = my_ui, server = my_server)
